config/routes.rb
class SubdomainPresent
def self.matches?(request)
request.subdomain.present?
end
end

class SubdomainBlank	
def self.matches?(request)
request.subdomain.blank?
end
end

Timetracker::Application.routes.draw do

  constraints(SubdomainPresent) do
match '/', to: 'accounts#new', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
	
  resources :bonus do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :slocs
  get 'work/index'

  get 'work/show'

  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'expenses/all' => 'expenses#all', :as => :all_expenses
  get 'rens/all' => 'rens#all', :as => :all_rens
  get 'stats/all' => 'stats#all', :as => :all_stats
  resources :locations
  resources :lineitems
  resources :schedules
  resources :invoices do
    resource :download, only: [:show]
  end
  resources :stats do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :expenses
	resources :expenses
	resources :stats
	resources :dashboards, only: [:show, :index]
	resources :projects
	resources :works do
	    member do
	    get 'rens/status' # Options: get, patch, put, post, or delete
	    put 'rens/status'
  	    get 'stats/status' # Options: get, patch, put, post, or delete
	    put 'stats/status'
  	    get 'bonus/status' # Options: get, patch, put, post, or delete
	    put 'bonus/status'
  end
	end
    resources :invoices
	resources :rens do
		get "status", on: :member
		post "status_update", on: :member
	end

	resources :messages, only: [:new, :create]
	resources :conversations, only: [:index, :show, :destroy] do
	  member do
	    post :reply, :restore
 	 end	
	  collection do
	    delete :empty_trash
	  end
	end
	resources :steps
	resources :rowts do
		get "rens", on: :member
	end
	devise_for :users, :controllers => { registrations: 'registrations' }
	resources :users do
		get "bonus", on: :member
		post "bonus_update", on: :member
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'    
	end

        

	resources :workers
	resources :worktypes
	resources :accounts, only: [:show]
	root 'dashboards#index', as: :subdomain_root
end

constraints(SubdomainBlank) do
resources :accounts, only: [:new, :create]
root 'welcomes#index'
end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :rowt
  belongs_to :sloc

  scope :this_month, -> { where(start_time: Time.now.beginning_of_month..Time.now.end_of_month) }
   scope :this_week, -> { where(start_time: Time.now-3.days..Time.now+7.days) }
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.this_month.order('start_time DESC')
    @rowts = Rowt.all
    @user = current_user
    @schedule = Schedule.where(:user_id => current_user.id)
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @user = current_user
    @schedule = Schedule.find(params[:id])
    redirect_to schedules_path if @schedule.user.id != current_user.id unless current_user.admin? unless current_user.dispatch?
  end

  # GET /schedules/new
  def new
    @user = current_user
    @office = @user.sloc
    @schedule = Schedule.new
    @office2 = Sloc.all
    @users = User.joins(:sloc).where(:sloc => current_user.sloc)
    @rowts = Rowt.joins(:sloc).where(:sloc => @office)
    redirect_to schedules_path if current_user.driver?
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
    @office = @schedule.sloc    
    redirect_to schedules_path if current_user.driver?
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_path, notice: 'Schedule was successfully created.' }
        format.json { render :index, status: :created, location: schedules_path }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    authorize @schedule
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:start_time, :user_id, :rowt_id, :sloc_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_editform.html.erb
<%= simple_form_for(@schedule) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :sloc, label: "Office", label_method: :officename, selected: [ @schedule.sloc], disabled: true %>
    <%= f.input :start_time, as: :datetime, ampm: true, minute_step: 5 %>
    <%= f.association :user, collection: [@users], selected: [@schedule.user] %>
    <%= f.association :rowt, label: "Route", collection: [@rowts], selected: [@schedule.rowt] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
<br>

app/views/schedules/_form.html.erb
<%= simple_form_for(@schedule) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :sloc, label: "Office", label_method: :officename, :selected => @user.sloc.id, disabled: true %>
    <%= f.input :start_time, as: :datetime, ampm: true, minute_step: 5 %>
    <%= f.association :user, collection: @users, :include_blank => false %>
    <%= f.association :rowt, label: "Route", collection: @rowts, :include_blank => false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>
<br>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'editform' %>

<%= link_to 'Show', @schedule, class: "btn btn-primary" %> |
<%= link_to 'Back', schedules_path, class: "btn btn-info" %>

app/views/schedules/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
<p id="notice"><%= notice %></p>

<h2 class="text-center">Listing Schedules</h2>
<div class="table-responsive">
<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Day</th>
      <th>Start time</th>
      <th>Driver</th>
      <th>Route</th>
<% if current_user.dispatch? || current_user.admin? then %>
      <th colspan="3"></th>
      <%else%>
        <th><%= colspan="1"%></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.start_time.strftime("%m""-""%d""-""%Y") %></td>
        <td><%= schedule.start_time.strftime("%A") %></td>
        <td><%= schedule.start_time.strftime("%I:%M %p") %></td>
        <td><%= schedule.user.name %></td>
        <td><%= schedule.rowt.name %></td>
        <td><%= link_to 'Show', schedule %></td>
<% if current_user.dispatch? || current_user.admin? then %>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <% if policy(schedule).destroy? %>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<% if current_user.dispatch? || current_user.admin? then %>
<%= link_to 'New Schedule', new_schedule_path, class: "btn btn-primary" %>
<%else%>




<div id="simple-calendar">
<h3>Schedule for <%=@user.name%></h3>
<%= month_calendar events: @schedule do |date, schedules| %>
<%= date.strftime("%d") %>

  <% schedules.each do |schedule| %>
    <div>
     <h4>Route: <%= schedule.rowt.name %></h4>
     <h4>Time: <%= schedule.start_time.strftime("%H:%M%p") %></h4><br>

    </div>
  <% end %>
<% end %>

</div>
<%end%>

    </div>
  </div>
  
</div>


<br><br>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', schedules_path, class: "btn btn-success" %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @schedule.start_time.strftime("%A") %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time.strftime("%I:%M %p") %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @schedule.user.name %>
</p>

<p>
  <strong>Route:</strong>
  <%= @schedule.rowt.name %>
</p>

<% if current_user.dispatch? || current_user.admin? then %>
<%= link_to 'Edit', edit_schedule_path(@schedule), class: "btn btn-warning" %> |
<%end%>
<%= link_to 'Back', schedules_path, class: "btn btn-primary" %>