config/routes.rb
class SubdomainPresent
def self.matches?(request)
request.subdomain.present?
end
end

class SubdomainBlank	
def self.matches?(request)
request.subdomain.blank?
end
end

Timetracker::Application.routes.draw do

  constraints(SubdomainPresent) do
match '/', to: 'accounts#new', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
	
  resources :bonus do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :slocs
  get 'work/index'

  get 'work/show'

  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'expenses/all' => 'expenses#all', :as => :all_expenses
  get 'rens/all' => 'rens#all', :as => :all_rens
  get 'stats/all' => 'stats#all', :as => :all_stats
  resources :locations
  resources :lineitems
  resources :schedules
  resources :invoices do
    resource :download, only: [:show]
  end
  resources :stats do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :expenses
	resources :expenses
	resources :stats
	resources :dashboards, only: [:show, :index]
	resources :projects
	resources :works do
	    member do
	    get 'rens/status' # Options: get, patch, put, post, or delete
	    put 'rens/status'
  	    get 'stats/status' # Options: get, patch, put, post, or delete
	    put 'stats/status'
  	    get 'bonus/status' # Options: get, patch, put, post, or delete
	    put 'bonus/status'
  end
	end
    resources :invoices
	resources :rens do
		get "status", on: :member
		post "status_update", on: :member
	end

	resources :messages, only: [:new, :create]
	resources :conversations, only: [:index, :show, :destroy] do
	  member do
	    post :reply, :restore
 	 end	
	  collection do
	    delete :empty_trash
	  end
	end
	resources :steps
	resources :rowts do
		get "rens", on: :member
	end
	devise_for :users, :controllers => { registrations: 'registrations' }
	resources :users do
		get "bonus", on: :member
		post "bonus_update", on: :member
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'    
	end

        

	resources :workers
	resources :worktypes
	resources :accounts, only: [:show]
	root 'dashboards#index', as: :subdomain_root
end

constraints(SubdomainBlank) do
resources :accounts, only: [:new, :create]
root 'welcomes#index'
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


def index
	@user = current_user
	@rowts = Rowt.all
	@steps = Step.all
	@rens = @user.rens.all

	@stats = @user.stats.all

	@r = @rens.includes(:rowt).joins(:rowt, :step).order("rens.dayt")
	@rr = @r.group_by(&:rowt)

end


end

app/views/projects/index.html.erb
<div class="col-md-12">
<div class="well">Hello! You can now track your work! | <%= link_to 'New Rowt', new_rowt_path, class: "btn btn-success" %> | <%= link_to 'New Step', new_step_path, class: "btn btn-success" %>
</div>

<br>
<h1>Listing Rowts</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>      
      <th>number of steps</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @rowts.each do |rowt| %>
      <tr>
        <td><%= rowt.name %></td>
        <td><%= rowt.steps.count %></td>
        <td><%= link_to 'View', rowt, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', rowt, class: "btn btn-warning" %></td>
        <td><%= link_to 'Delete', rowt, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rowt', new_rowt_path, class: "btn btn-success" %>


<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<h1>Listing Steps</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Value</th>
      <th>Rowt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.name %></td>
        <td><%= step.address %></td>
        <td><%= step.value %></td>
        <td><%= step.rowt.name %></td>
        <td><%= link_to 'Show', step, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_step_path(step), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path, class: "btn btn-success" %>
<br>
<br>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Visit?</th>
      <th>Rowt Name</th>
      <th>Value</th>
      <th>Step Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rens.each do |ren| %>
      <tr>
        <td><%= ren.visit %></td>
        <td><%= ren.rowt.name %></td>
        <td><%= ren.step.value %></td>
        <td><%= ren.step.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>



    <% @rr.each do |dayt, ren| %>
     
      <%= dayt.inspect %><br><br><br>
      <%= ren.inspect %>
      <%= dayt.inspect %>
      <% ren.each do |r|%>
        <%= r.dayt %>
        |||<br>
        <br>
      <%end%>
              <br>
    <%end%>


<br>
adsfasdfas
<br><br><br><br>
<% @stats.each do |stats| %>
  <%= stats.name %>
  <%= stats.amount %>
  <%= stats.dayt %>,
<%end%>

<br>
<%=Time.now.strftime("%Y%m")%>