config/routes.rb
class SubdomainPresent
def self.matches?(request)
request.subdomain.present?
end
end

class SubdomainBlank	
def self.matches?(request)
request.subdomain.blank?
end
end

Timetracker::Application.routes.draw do

  constraints(SubdomainPresent) do
match '/', to: 'accounts#new', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
	
  resources :bonus do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :slocs
  get 'work/index'

  get 'work/show'

  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'expenses/all' => 'expenses#all', :as => :all_expenses
  get 'rens/all' => 'rens#all', :as => :all_rens
  get 'stats/all' => 'stats#all', :as => :all_stats
  resources :locations
  resources :lineitems
  resources :schedules
  resources :invoices do
    resource :download, only: [:show]
  end
  resources :stats do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :expenses
	resources :expenses
	resources :stats
	resources :dashboards, only: [:show, :index]
	resources :projects
	resources :works do
	    member do
	    get 'rens/status' # Options: get, patch, put, post, or delete
	    put 'rens/status'
  	    get 'stats/status' # Options: get, patch, put, post, or delete
	    put 'stats/status'
  	    get 'bonus/status' # Options: get, patch, put, post, or delete
	    put 'bonus/status'
  end
	end
    resources :invoices
	resources :rens do
		get "status", on: :member
		post "status_update", on: :member
	end

	resources :messages, only: [:new, :create]
	resources :conversations, only: [:index, :show, :destroy] do
	  member do
	    post :reply, :restore
 	 end	
	  collection do
	    delete :empty_trash
	  end
	end
	resources :steps
	resources :rowts do
		get "rens", on: :member
	end
	devise_for :users, :controllers => { registrations: 'registrations' }
	resources :users do
		get "bonus", on: :member
		post "bonus_update", on: :member
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'    
	end

        

	resources :workers
	resources :worktypes
	resources :accounts, only: [:show]
	root 'dashboards#index', as: :subdomain_root
end

constraints(SubdomainBlank) do
resources :accounts, only: [:new, :create]
root 'welcomes#index'
end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	before_action :load_activities, only: [:index, :show, :new, :edit]
	skip_before_filter :check_payment2
	skip_before_filter :check_sloc

	def index
		@rowts = Rowt.all
		@user = current_user
		@partial = @user.userlevel
		@schedules = Schedule.all
	    @schedule = Schedule.where(:user_id => current_user.id).where(start_time: Time.now-3.days..Time.now+7.days).order('start_time ASC')
	    @schedule2 = @schedule.where(start_time: Time.now-3.days..Time.now+7.days)
	    @driverrens = @user.rens.this_month.all
	    @driverstats = @user.stats.this_month.all
	    @expenses = @user.expenses.this_month.all
	    @income = @user.stats.this_month.all
	    @officeuser = @user.sloc
	    @workers = User.where(:sloc => @officeuser)
		@test = Stat.pending	    

		#ren, stat, or bonu with submitted or denied status
	    @pendingrens = Ren.pending
	    @pendingbonus = Bonu.pending
	    @pendingstats = Stat.pending
	    @pendingwork = (@pendingrens + @pendingstats + @pendingbonus)

	    @rejectedrens = Ren.rejected
	    @rejectedbonus = Bonu.rejected
	    @rejectedstats = Stat.rejected
	    @rejectedwork = (@rejectedrens + @rejectedstats + @rejectedbonus)	    

	    #calendar
	    @schedule2 = Schedule.where("start_time >= ? and sloc_id >= ?", 1.day.from_now, @user.sloc_id).order('start_time ASC')
	    @schedule3 = Schedule.joins(:user).where("start_time >= ?", 1.days.ago).where("start_time <= ?", 1.day.from_now).where("users.sloc_id >= ?", @user.sloc_id).order('start_time ASC')

	    #Admin
	    @aworkers = User.all
	    @slocs = Sloc.all
	    @activities = PublicActivity::Activity.all
	end

	def show
	end

	private

def find_office
	@driversrens
end


def load_activities
  @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
end

	def premiumvisit
		@ren = @driverrens.each
		@ren.visit()		
	end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_admin.html.erb
<br><br><br>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 button-wrapper">
        <%= link_to "Work waiting approval: #{@pendingwork.count} ", works_path, class: "btn btn-lg btn-block btn-primary" %>   </div>
    <div class="col-md-3 button-wrapper">       
        <%= link_to 'Messages', conversations_path, class: "btn btn-lg btn-block btn-success" %>
    </div>
    <div class="col-md-3 button-wrapper">
        <%= link_to 'New Schedule', new_schedule_path, class: "btn btn-lg btn-block btn-warning" %>
    </div>
    <div class="col-md-3 button-wrapper">
        <%= link_to 'Workers', workers_path, class: "btn btn-lg btn-block btn-danger" %>
    </div>
  </div>
</div>
<% if Sloc.nil? %>
<%= "fasfdasFD" %>
<% end %>
<br><br><br>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
    <h3 class="text-center">Offices</h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Office Name</th>
      <th>Office Address</th>      
      <th>Drivers at office</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @slocs.each do |sloc| %>
      <tr>
        <td><%= sloc.officename %></td>
        <td><%= sloc.address%></td>
        <td><%= sloc.users.count %></td>
        <td><%= link_to 'View', sloc, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', sloc, class: "btn btn-warning" %></td>
        <td><%= link_to 'Delete', sloc, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Office', new_sloc_path, class: "btn btn-success" %>
</div></div></div>

  
<hr>
<div class="container">
  <div class="row">
    <div class="col-xs-12">

    <h3 class="text-center">Listing Routes</h3>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>      
      <th>Address</th>
      <th>Office</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @rowts.each do |rowt| %>
      <tr>
        <td><%= rowt.name %></td>
        <td><%= rowt.steps.count %></td>
        <td><%= rowt.sloc.officename %></td>
        <td><%= link_to 'View', rowt, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', rowt, class: "btn btn-warning" %></td>
        <td><%= link_to 'Delete', rowt, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Rowt', new_rowt_path, class: "btn btn-success" %>
<hr>
</div></div></div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
<div id="simple-calendar">
<h2 class="text-center">Schedule for everyone</h2>
<%= month_calendar events: @schedules do |date, schedules| %>
<%= date.strftime("%d") %>

  <% schedules.each do |schedule| %>
    <div>
     <h4>Route: <%= schedule.rowt.name %></h4>
     <h4>Time: <%= schedule.start_time.strftime("%H:%M%p") %></h4><br>

    </div>
  <% end %>
<% end %>

</div></div></div></div>
<br><br>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
  <h3 class="text-center"><%= "Workers #{@aworkers.count}"%></h3>
        <table class="table table-bordered table-hover">
        <thead>
          <tr>
          <th>Name</th>
          <th>Type</th>
          <th>Office</th>
          </tr>
        </thead>
        <tbody>
          <% @aworkers.each do |s| %>
            <tr>
              <td><%= s.name  %></td>
              <td><%= s.userlevel  %></td>
              <td><%= if s.sloc_id? then s.sloc.officename else "Not assigned to an office" end %></td>
            </tr>
          <% end %>
        </tbody>
  </table>
  <br><br><br><br>
  </div></div></div>

  <%= @user.inspect%>

app/views/dashboards/_dispatch.html.erb

<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 button-wrapper">
        <%= link_to "Work waiting approval: #{@pendingwork.count} ", works_path, class: "btn btn-lg btn-block btn-primary" %>   </div>
    <div class="col-md-4 button-wrapper">       
        <%= link_to 'Messages', conversations_path, class: "btn btn-lg btn-block btn-success" %>
    </div>
    <div class="col-md-4 button-wrapper">
        <%= link_to 'New Schedule', new_schedule_path, class: "btn btn-lg btn-block btn-warning" %>
    </div>

  </div>
</div>

<br><br><br>

  <h2><%= " #{@user.sloc.officename} schedule for the next 24 hours"%></h2>
        <table class="table table-bordered table-hover">
        <thead>
          <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Route</th>
          <th>Driver</th>
          </tr>
        </thead>
        <tbody>
          <% @schedule3.each do |s| %>
            <tr>
              <td><%= s.start_time.strftime("%b %d, %Y")  %></td>
              <td><%= s.start_time.strftime("%I:%M %p")  %></td>
              <td><%= s.rowt.name %></td>
              <td><%= s.user.name %></td>
            </tr>
          <% end %>
        </tbody>
  </table>


<br><br>


<div class="col-md-8 col-md-offset-2">
  <h2><%= "#{@officeuser.officename} Staff"%></h2>

  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @workers.each do |user| %>
            <tr>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= user.firstname %></td>
              <td><%= user.lastname %></td>
              <td><%= user.email %></td>
              <td><%= user_status(user) %></td>
              <td><%= link_to 'Send message', new_message_path(to: user.id), class: 'btn btn-default btn-sm' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

        <h3 class="extra-margin-top">Invite User</h3>

        <%= simple_form_for(User.new, url: user_invitation_path, html: { class: 'form-inline'} ) do |f| %>
        <%= f.input :email, placeholder: 'Email', label: false %>
        <%= f.button :submit, 'Add Worker', class: 'btn-primary' %>
        <%end%>                

    </div>
   </div>
  </div>
<br><br>

app/views/dashboards/_driver.html.erb

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 button-wrapper">
        <%= link_to 'New Run', rowts_path, class: "btn btn-lg btn-block btn-primary" %>    </div>
    <div class="col-sm-3 button-wrapper">       
        <%= link_to 'New Stat', new_stat_path, class: "btn btn-lg btn-block btn-success" %>
    </div>
    <div class="col-sm-3 button-wrapper">
        <%= link_to 'New Expense', new_expense_path, class: "btn btn-lg btn-block btn-warning" %>
    </div>
    <div class="col-sm-3 button-wrapper">
        <%= link_to 'New Invoice', new_invoice_path, class: "btn btn-lg btn-block btn-info" %>
    </div>
  </div>
</div>
<br>
<div class="col-xs-12" id="simple-calendar">
<h2>Schedule</h2>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Day</th>
      <th>Start time</th>
      <th>Route</th>
      <th>Run Route</th>
    </tr>
  </thead>

  <tbody>
    <% @schedule.each do |schedule| %>
      <tr>
        <td><%= schedule.start_time.strftime("%A: %B %d") %></td>
        <td><%= schedule.start_time.strftime("%I:%M %p") %></td>
        <td><%= schedule.rowt.name %></td>
        <td><%= link_to "Run Route", rens_rowt_path(schedule.rowt.id), class: "btn btn-primary"  %></td>
        <%end%>
      </tr>
  </tbody>
</table>
<br>
</div>





<br>
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-6"><h2>Completed Rens for Month</h2>

<table class="table table-striped table-bordered table-condensed">
<thead>
  <tr>
    <th colspan="1">Date</th>
    <th colspan="1">Status</th>
    <th colspan="1">Rowt</th>
    <th colspan="1">Stops</th>
  </tr>
</thead>
<tbody>
    <% @driverrens.each do |rs| %>
  <tr>
      <td><%= rs.dayt.strftime("%m""-""%d""-""%Y") %></td>
      <td class="<%= rs.tat %>"><%= rs.tat %></td>
      <td><%= link_to rs.rowt.name, ren_path(rs), class: "btn btn-success btn-block"  %></td>
      <td><%= rs.rvisit.reject!(&:empty?).count + rs.pvisit.reject!(&:empty?).count %></td>
    <% end %>
</tbody>                                        
</table>
</div>
      




      <div class="col-sm-6">
      <h2>Completed Stats for Month</h2>

<table class="table table-bordered table-striped  table-condensed">
  <thead>
    <tr>
      <th>Date</th>
      <th>Status</th>
      <th>Amount</th>
      <th>Facility Name</th>
    </tr>
  </thead>

  <tbody>
    <% @driverstats.each do |stat| %>
      <tr>
        <td><%= stat.dayt.strftime("%m""-""%d""-""%Y") %></td>
        <td class="<%= stat.tat %>"><%= stat.tat %></td>
        <td><%= number_to_currency(stat.amount, unit: "$") %></td>
        <td><%= link_to stat.name, stat_path(stat) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
</div>
    </div>
</div>

app/views/dashboards/index.html.erb
<div class="text-center"> <h1>Dashboard</h1></div>
<div class='container'>
<div class='row'>
  <div class="col-sm-9">

</div>
</div>
</div>
<hr />

<%= render @partial %>

app/views/dashboards/show.html.erb
<h1>Dashboards#show</h1>
<p>Find me in app/views/dashboards/show.html.erb</p>