config/routes.rb
class SubdomainPresent
def self.matches?(request)
request.subdomain.present?
end
end

class SubdomainBlank	
def self.matches?(request)
request.subdomain.blank?
end
end

Timetracker::Application.routes.draw do

  constraints(SubdomainPresent) do
match '/', to: 'accounts#new', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
	
  resources :bonus do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :slocs
  get 'work/index'

  get 'work/show'

  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'expenses/all' => 'expenses#all', :as => :all_expenses
  get 'rens/all' => 'rens#all', :as => :all_rens
  get 'stats/all' => 'stats#all', :as => :all_stats
  resources :locations
  resources :lineitems
  resources :schedules
  resources :invoices do
    resource :download, only: [:show]
  end
  resources :stats do
		get "status", on: :member
		post "status_update", on: :member
	end
  resources :expenses
	resources :expenses
	resources :stats
	resources :dashboards, only: [:show, :index]
	resources :projects
	resources :works do
	    member do
	    get 'rens/status' # Options: get, patch, put, post, or delete
	    put 'rens/status'
  	    get 'stats/status' # Options: get, patch, put, post, or delete
	    put 'stats/status'
  	    get 'bonus/status' # Options: get, patch, put, post, or delete
	    put 'bonus/status'
  end
	end
    resources :invoices
	resources :rens do
		get "status", on: :member
		post "status_update", on: :member
	end

	resources :messages, only: [:new, :create]
	resources :conversations, only: [:index, :show, :destroy] do
	  member do
	    post :reply, :restore
 	 end	
	  collection do
	    delete :empty_trash
	  end
	end
	resources :steps
	resources :rowts do
		get "rens", on: :member
	end
	devise_for :users, :controllers => { registrations: 'registrations' }
	resources :users do
		get "bonus", on: :member
		post "bonus_update", on: :member
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'    
	end

        

	resources :workers
	resources :worktypes
	resources :accounts, only: [:show]
	root 'dashboards#index', as: :subdomain_root
end

constraints(SubdomainBlank) do
resources :accounts, only: [:new, :create]
root 'welcomes#index'
end
end

app/models/ren.rb
class Ren < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
    enum tat: [:submitted, :approved, :denied]

  belongs_to :user
  belongs_to :rowt
  has_one :lineitem
  has_one :invoice, through: :lineitem
  has_one :lineitem
  has_one :sloc, through: :user
    scope :this_month, -> { where(created_at: Time.now.beginning_of_month..Time.now.end_of_month) }
	scope :pending, -> { where(:tat => ["0", "2"]) }
        scope :rejected, -> { where(:tat => ["2"]) }
	scope :dispatch, -> { where(:userlevel => ["dispatch"]) }
	scope :dispatchrens, -> { dispatch.pending }

def week
  self.dayt.strftime('%W')
end

end

app/controllers/rens_controller.rb
class RensController < ApplicationController
  before_action :set_ren, only: [:show, :edit, :update, :destroy]

skip_before_action :verify_authenticity_token


  # GET /rens
  # GET /rens.json
  def index
    @user = current_user
    @rens = @user.rens.this_month.all
    @allrens = Ren.all
    @paylevel = @user.paylevel

  end

  def all
    @user = current_user
    @rens = @user.rens.all
    @search = @rens.search(params[:q])
    @rensresults = @search.result
    @paylevel = @user.paylevel
  end



  # GET /rens/1
  # GET /rens/1.json
  def show
    @paylevel = @ren.user.paylevel
    @ren = Ren.find(params[:id])
    @user = current_user
    @flatrate = @user.flatrate
    @pvalue = @user.premiumstop
    @rvalue = @user.regularstop
    @visited = (@ren.rvisit + @ren.pvisit) #array of ids for visited
    @visitedstep = Step.where(id: [@visited])
    @regularvisit = @visitedstep.where(steplevel: 0)
    @premiumvisit = @visitedstep.where(steplevel: 1)
    @total = (@premiumvisit.count * @pvalue) + (@regularvisit.count * @rvalue)




    @pstepid = @ren.pvisit
    @pstep = Step.where(id: [@pstepid])
    @stepid = @ren.rvisit
    @rstep = Step.where(id: [@stepid])
    @ss = @pstep.concat @rstep
    @stepvaluetotal = @ss.inject(0){|sum,e| sum + e.stepvalue }
    @pertotal = (@stepvaluetotal * (@user.percent * 0.01))

    redirect_to rens_path if @ren.user.id != current_user.id unless current_user.admin? unless current_user.dispatch?
  end

  # GET /rens/new
  def new
    ###ren is set through rowt/ren
    @k = "1"
    @user = current_user
    @steps = Step.all
    @ren = Ren.new
    @rens = @user.rens.all
    @rowt = Rowt.first
    @r = Step.where(:rowt_id => @k)
  end

  # GET /rens/1/edit
  def edit
    @ren = Ren.find(params[:id])
    @rowtt = @ren.rowt
    @steps = Step.all
    @s = Step.where(:rowt_id => @rowtt)
    @user = current_user
    @k = "1"
    @r = Step.where(:rowt_id => @k)
    @visit = Ren.find_by(params[:visit])

   @pstepid = @ren.pvisit
    @pstep = Step.where(id: [@pstepid])

    @stepid = @ren.rvisit
    @rstep = Step.where(id: [@stepid])
    redirect_to rens_path if @ren.user.id != current_user.id || @ren.tat = "approved"
  end

  # POST /rens
  # POST /rens.json
  def create
      @ren = Ren.new(ren_params)

    respond_to do |format|
      if @ren.save
        format.html { redirect_to @ren, notice: 'Run added successfully!' }
        format.json { render :show, status: :created, location: @ren }
      else
        format.html { render :new }
        format.json { render json: @ren.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rens/1
  # PATCH/PUT /rens/1.json
  def update
    respond_to do |format|
      if @ren.update(ren_params)
          authorize @ren
        format.html { redirect_to @ren, notice: 'Ren was successfully updated.' }
        format.json { render :show, status: :ok, location: @ren }
      else
        format.html { render :edit }
        format.json { render json: @ren.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rens/1
  # DELETE /rens/1.json
  def destroy
    @ren.destroy
    respond_to do |format|
      format.html { redirect_to rens_url, notice: 'Ren was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def status
    @ren = Ren.find(params[:id])
    @rowtt = @ren.rowt
    @stepid = @ren.rvisit + @ren.pvisit
    @step = Step.where(id: [@stepid])
    @driver = @ren.user

    @pvalue = @driver.premiumstop
    @rvalue = @driver.regularstop
    @pvisit = @ren.pvisit.reject!(&:empty?).count
    @rvisit = @ren.rvisit.reject!(&:empty?).count

    @ptotal = @pvalue * @pvisit
    @rtotal = @rvalue * @rvisit
    @total = (@ptotal + @rtotal)
  redirect_to rens_path if current_user.driver?
  end

  def status_update
    @ren = Ren.find params[:id]
    respond_to do |format|
      if @ren.update(ren_params)
        format.html { redirect_to works_path, notice: 'Work status was successfully updated.' }
        format.json { redirect_to controller: :works, action: :index, status: :ok, location: :works }
      else
        format.html { render :status }
        format.json { render json: @ren.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ren
      @ren = Ren.find(params[:id])
    end

          def rens_params(my_params)
            my_params.permit(:ren_id, :step_id, :user_id, :visit, :dayt)
          end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ren_params
      params.require(:ren).permit(:dayt, :user_id, :rowt_id, :tat, {:rvisit => []}, {:pvisit => []})
    end
end

app/helpers/rens_helper.rb
module RensHelper
end

app/views/rens/_dedit.html.erb
<p>
  <h1><%= @rowtt.name %> Route</h1>
</p>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Type</th>
    </tr>
  </thead>

  <tbody>
    <% @rstep.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.address %></td>
        <td><%= f.steplevel %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Type</th>
    </tr>
  </thead>

  <tbody>
    <% @pstep.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.address %></td>
        <td><%= f.steplevel %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= simple_form_for(@ren) do |f| %>
  <% if @ren.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ren.errors.count, "error") %> prohibited this ren from being changed:</h2>

      <ul>
      <% @ren.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-inputs">
    <%= f.input :tat, as: :radio_buttons, label: 'Approval Status', collection: ["submitted", "approved", "denied"] %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

 <%end%>

app/views/rens/_flat.html.erb
<div class="table-responsive">
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Type</th>
      <th>Earning</th>
    </tr>
  </thead>

  <tbody>
    <% @ss.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.address %></td>
        <td><%= f.steplevel %></td>
        <td>FLAT RATE </td>
      </tr>
    <% end %>
  </tbody>
  <thead>
<tr>
<th></th>
<th></th>
<th></th>
  <th>Total</th>
</tr>
</thead>
  <tr>
  <td></td>
  <td></td>
  <td></td>
    <td><%= number_to_currency(@flatrate, :unit => "$") %></td>
  </tr>
</table>
</div>

app/views/rens/_flati.html.erb
<div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Route</th>
              <th>Invoiced?</th>
              <th>Status</th>
              <th>Visit</th>
              <th>Date</th>
              <th>Run value</th>
              <th>Office</th>
              <TH>Invoiced?</TH>
            </tr>
          </thead>

          <tbody>
            <% @rens.each do |ren| %>
              <tr>
                <td><%= link_to ren.rowt.name, ren, class: "btn btn-primary" %></td>
                <td><%= if ren.lineitem.nil? then "Not invoiced" else "Invoiced" end %></td>
                <td class="<%= ren.tat %>"><%= ren.tat %></td>
                <td><%= (ren.rvisit.reject(&:empty?).count + ren.pvisit.reject(&:empty?).count) %></td>
                <td><%= ren.dayt.strftime("%m""-""%d""-""%Y") %></td>
                <td><%= number_to_currency(ren.user.flatrate, unit: "$" )%></td>
                <td><%= ren.rowt.sloc.officename %></td>
                <td><%= if ren.lineitem.present? then "Invoiced" else  link_to 'Delete Run', ren, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
</div>

app/views/rens/_form.html.erb
<%= form_for(@ren) do |f| %>
  <% if @ren.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ren.errors.count, "error") %> prohibited this ren from being saved:</h2>

      <ul>
      <% @ren.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.hidden_field :rowt_id, value: @rowtt.id %>
  </div>


<div class="field">
  <%= f.label "Visiting Stops" %><br />
  <%= f.collection_check_boxes :visit, @s, :id, :name,, :input_html => { :disabled => true }  class: "checkbox" do |b| %>
    <div class="checkbox">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
</div>

<div class="field">
  <%= f.label "Date" %><br>
  <%= f.date_select :dayt %>
</div>
<br>
<br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>

  <% end %>

app/views/rens/_perc.html.erb
<div class="table-responsive">
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Stop Value</th>
      <th>Earning</th>
    </tr>
  </thead>

  <tbody>
    <% @ss.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.address %></td>
        <td><%= f.stepvalue %></td>
        <td><%= @user.percent %>%</td>
      </tr>
    <% end %>
  </tbody>
  <thead>
<tr>
<th></th>
<th></th>
<th></th>
  <th>Total</th>
</tr>
</thead>
  <tr>
  <td></td>
  <td></td>
  <td></td>
    <td><%= number_to_currency(@pertotal, :unit => "$") %></td>
  </tr>
</table>
</div>

<br>
<br>

app/views/rens/_perci.html.erb
<div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Route</th>
              <th>Invoiced?</th>
              <th>Status</th>
              <th>Visit</th>
              <th>Date</th>
              <th>Office</th>
              <TH>Delete</TH>
            </tr>
          </thead>

          <tbody>
            <% @rens.each do |ren| %>
              <tr>
                <td><%= link_to ren.rowt.name, ren, class: "btn btn-primary" %></td>
                <td><%= if ren.lineitem.nil? then "Not invoiced" else "Invoiced" end %></td>
                <td class="<%= ren.tat %>"><%= ren.tat %></td>
                <td><%= (ren.rvisit.reject(&:empty?).count + ren.pvisit.reject(&:empty?).count) %></td>
                <td><%= ren.dayt.strftime("%m""-""%d""-""%Y") %></td>
                <td><%= ren.rowt.sloc.officename %></td>
                <td><%= if ren.lineitem.present? then "Invoiced" else  link_to 'Delete Run', ren, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
</div>

<br><br>

app/views/rens/_perstop.html.erb
<div class="table-responsive">
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Type</th>
      <th>Earning</th>
    </tr>
  </thead>

  <tbody>
    <% @ss.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.address %></td>
        <td><%= f.steplevel %></td>
        <td><%= if f.steplevel == "regular" then number_to_currency(@rvalue, :unit => "$") else number_to_currency(@pvalue, :unit => "$") end %></td>
      </tr>
    <% end %>
  </tbody>
  <thead>
<tr>
<th></th>
<th></th>
<th></th>
  <th>Total</th>
</tr>
</thead>
  <tr>
  <td></td>
  <td></td>
  <td></td>
    <td><%= number_to_currency(@total, :unit => "$") %></td>
  </tr>
</table>
</div>

sdsdsds

app/views/rens/_perstopi.html.erb
<div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Route</th>
              <th>Invoiced?</th>
              <th>Status</th>
              <th>Visit</th>
              <th>Date</th>
              <th>Run value</th>
              <th>Office</th>
              <TH>FLATRATE</TH>
            </tr>
          </thead>

          <tbody>
            <% @rens.each do |ren| %>
              <tr>
                <td><%= link_to ren.rowt.name, ren, class: "btn btn-primary" %></td>
                <td><%= if ren.lineitem.nil? then "Not invoiced" else "Invoiced" end %></td>
                <td class="<%= ren.tat %>"><%= ren.tat %></td>
                <td><%= (ren.rvisit.reject(&:empty?).count + ren.pvisit.reject(&:empty?).count) %></td>
                <td><%= ren.dayt.strftime("%m""-""%d""-""%Y") %></td>
                <td><%= number_to_currency((ren.rvisit.reject(&:empty?).count * @user.regularstop) + (ren.pvisit.reject(&:empty?).count * @user.premiumstop), :unit => "$") %></td>
                <td><%= ren.rowt.sloc.officename %></td>
                <td><%= if ren.lineitem.present? then "Invoiced" else  link_to 'Delete Run', ren, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" end %></td>
                <td><%=ren.user.flatrate %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
</div>

app/views/rens/all.html.erb
<div class="container">

<h2 class="text-center">All Runs</h2>

	<div class="row">
	<span class="pull-right">
		<%= link_to 'New Run', rowts_path, class: "btn btn-success"  %>
	</span>
	</div>
	<hr />
<div class="row">

<%= render "rens/all/" + @paylevel %>


</div>
<br>
  </div>

app/views/rens/edit.html.erb
<div class="container">
	  <div class="row">
    	<div class="col-xs-12">

	    	<h1>Editing Run</h1>

			<%= render 'dedit' %>

			<%= link_to 'Show', @ren, class: "btn btn-success" %> |
			<%= link_to 'Back', rens_path, class: "btn btn-warning" %>
		</div>
	</div>
</div>

app/views/rens/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

        <h2 class="text-center">Runs for last 4 weeks</h2>

          <span class="pull-right">
            <%= link_to 'New Run', rowts_path, class: "btn btn-primary" %> | <%= link_to 'All Runs', all_rens_path, class: "btn btn-success"  %>
          </span>
          </div>
    <div class="col-xs-12">
        <hr>

        <%= render @paylevel + "i" %>
        <br>

        <%= link_to 'Complete a Run', rowts_path, class: "btn btn-primary" %>      
    </div>
  </div>
</div>

<%= (@rens.count * (@user.percent * 0.01)) %>

app/views/rens/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
<h1>New Ren</h1>

<%= render 'form' %>

<%= link_to 'Back', rens_path %>
</div>
</div>
</div>

app/views/rens/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">


<p>
  <strong>Date:</strong>
  <%= @ren.dayt.strftime("%m""-""%d""-""%Y")  %>

</p>

<p>
  <strong>rowt:</strong>
    <%= @ren.rowt.name  %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ren.tat %>
</p>
<br>
  
<%= button_to "delete", @ren, :method => :delete, class: "btn btn-danger"  %>
<hr>
    <%= render @paylevel %>


<br>

<div class="row">
    <div class="col-xs-4">
    <% if @ren.tat = "submitted" || "rejected" %>
<%= link_to 'Edit', edit_ren_path(@ren), class: "btn btn-warning" %> |
<%end%>
<%= link_to 'Back', rens_path, class: "btn btn-primary" %> 
    </div>
    <div class="col-xs-8">
    </div>

</div></div></div>
<br><br>

app/views/rens/status.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
<%= render 'statusform' %>
<br>
<%= link_to 'Back', works_path, class: "btn btn-warning" %>
</div></div></div>